bike.challenge:
  base-url: "https://gbfs.urbansharing.com/oslobysykkel.no"
  station-info: "/station_information.json"
  station-status: "/station_status.json"

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
